### ISSUE TITLE
Wrong date on mentor confirm email

### ISSUE THREAD

**Issue by kapil1garg** [CoderDojoChi/coderdojochi#123]
Was messing around with class registration and found these issues (doesn't seem to affect Intro Meetings): 

Registered for 3/14 @ Barry
![screen shot 2015-03-07 at 2 02 43 pm](https://cloud.githubusercontent.com/assets/3069370/6543079/cce805ae-c4d2-11e4-8417-db78d04d0ed8.png)

Registered for 3/21 @ Academy for Global Citizenship
![screen shot 2015-03-07 at 2 04 40 pm](https://cloud.githubusercontent.com/assets/3069370/6543083/ef7d2c0c-c4d2-11e4-8c41-2e0b82f170bc.png)

Registered for 3/28 @ SapientNitro
![screen shot 2015-03-07 at 2 05 32 pm](https://cloud.githubusercontent.com/assets/3069370/6543084/1258eebe-c4d3-11e4-8dae-5533a9c9354f.png)

All have the same date displayed, so it looks like it might be a hard coded value

**Comment by karbassi** [comment]
Great catch. The error was when we created **volunteer** start/end time that were different than the **class** start/end time, the migrations didn't run correctly. The change was done in 46f0eefa28f4f5ed3bed79159c844ac9464b4af0.

The fix is to manually update the old db records that were created before that feature was added. All new features are fine.
