### ISSUE TITLE
Reverse order of past classes/meetings in /admin

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#240]

**Comment by ZahidP** [comment]
https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/admin.py#L57
and
https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/admin.py#L88 
? Are we essentially adding a "-" to these lines or is there more to it?

**Comment by bkellgren** [comment]
That would reorder for the default admin views, we would want to make the same update on the following lines as well to update in our custom admin view...

https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/views.py#L1056
https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/views.py#L1062
https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/views.py#L1070
https://github.com/CoderDojoChi/coderdojochi/blob/develop/coderdojochi/views.py#L1076

**Comment by pjsier** [comment]
So I changed the ordering (just added the "-" in front of start_date in both lines on admin.py, and on lines 1062 (past_sessions) and 1076 (past_meetings) in views.py. I didn't change it for the other two you mentioned (1056 and 1070) because those are for upcoming classes/meetings, and for those I actually figured we would want the soonest in the future to be first

Commit log is here on my fork https://github.com/pjsier/coderdojochi/commit/642429d04088c17e19138fbdcc9d8ac47d326678

Should I submit a pull request?

**Comment by bkellgren** [comment]
Good call on the other two for upcoming, you are right those shouldn't be reversed.  Yeah go ahead and open a PR against coderdojochi/coderdojochi:develop  (it should be the default when you open the PR via github)

**Comment by karbassi** [comment]
Can this be closed then?

cc: @bkellgren @pjsier

**Comment by pjsier** [comment]
@karbassi yep! this can be closed

**Comment by rebeldroid12** [comment]
@karbassi i think this is completed.

**Comment by karbassi** [comment]
Yes! This has been completed.

Thanks @rebeldroid12 for the reminder.
