### ISSUE TITLE
Update all date pickers (non-admin) to use bootstrap-datepicker

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#74]
Seems like some people are having issues with the birthday for their profile.

Let's use https://github.com/eternicode/bootstrap-datepicker/

**Comment by karbassi** [comment]
![screen shot 2015-02-09 at 16 58 55](https://cloud.githubusercontent.com/assets/17738/6117803/083afbee-b07d-11e4-9e45-681b12e432bd.png)
![screen shot 2015-02-09 at 16 59 03](https://cloud.githubusercontent.com/assets/17738/6117805/0b064522-b07d-11e4-8377-52c135776853.png)
![screen shot 2015-02-09 at 16 59 09](https://cloud.githubusercontent.com/assets/17738/6117806/106bf098-b07d-11e4-9cfb-b68b33ed308d.png)

**Comment by bkellgren** [comment]
I prefer http://amsul.ca/pickadate.js/ which has really good mobile support also, preference?

**Comment by karbassi** [comment]
First time seeing pickadate.js. I like it. 

Pros? Cons?

**Comment by bkellgren** [comment]
It’s got nice mobile support, I’ll have some time to add it tonight


On February 9, 2015 at 5:06:33 PM, Ali Karbassi (notifications@github.com) wrote:

First time seeing pickadate.js. I like it.

Pros? Cons?

**Comment by karbassi** [comment]
@bkellgren Can you upload a screenshot here?

**Comment by bkellgren** [comment]
I already implemented it, check it out on the live site


On February 9, 2015 at 6:28:01 PM, Ali Karbassi (notifications@github.com) wrote:

@bkellgren Can you upload a screenshot here?

**Comment by karbassi** [comment]
@bkellgren I ask because I don't want to create a fake guardian account just to see the date picker. Is it up on staging by chance?

**Comment by bkellgren** [comment]
i haven’t pushed to staging no,  you could do it locally…

screen shot: https://www.dropbox.com/s/mnnoesnr8yb6yhu/Screenshot%202015-02-09%2018.36.22.png?dl=0

and it will dynamically limit it to ages 7-17 up to the day the way i have it configured



On February 9, 2015 at 6:34:50 PM, Ali Karbassi (notifications@github.com) wrote:

@bkellgren I ask because I don't want to create a fake guardian account just to see the date picker. Is it up on staging by chance?
